name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version and Tag
        id: version
        uses: starburst997/auto-version@v1
        with:
          update-major-minor: true

      - name: Publish Extension
        uses: starburst997/code-extension-publish@v1
        with:
          version: ${{ steps.version.outputs.version }}
          vsce-pat: ${{ secrets.VSCE_PAT }}
          ovsx-pat: ${{ secrets.OVSX_PAT }}
          platforms: "darwin-x64,darwin-arm64"

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          artifacts: |
            *.vsix
