name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Initialize custom bot
        id: bot
        uses: starburst997/custom-bot-init@v1
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.bot.outputs.token }}

      - name: Tag Version
        id: version
        uses: starburst997/auto-version@v1
        with:
          git-push: false

      - name: Publish Extension
        uses: starburst997/code-extension-publish@v1
        with:
          version: ${{ steps.version.outputs.version }}
          vsce-pat: ${{ secrets.VSCE_PAT }}
          ovsx-pat: ${{ secrets.OVSX_PAT }}
          platforms: "darwin-x64,darwin-arm64"

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
          git-push: true
          artifacts: |
            *.vsix
